version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - app-network

  kolekcija:
    build:
      context: ./kolekcija
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    environment:
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    networks:
      - app-network
  poruka:
    build:
      context: ./poruka
    ports:
      - "8002:8002"
    depends_on:
      - dynamodb-local
    environment:
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
