version: "3.8"
services:
  recenzija:
    image: recenzija-fastapi
    ports:
      - "8002:8000"
    networks:
      - mreza
    deploy:
      replicas: 2

  kolekcija:
    image: kolekcija-fastapi
    ports:
      - "8005:8000"
    networks:
      - mreza
    deploy:
      replicas: 2

  korisnik:
    image: korisnik-fastapi
    ports:
      - "8004:8000"
    networks:
      - mreza
    deploy:
      replicas: 2

  poruka:
    image: poruka-fastapi
    ports:
      - "8003:8000"
    networks:
      - mreza
    deploy:
      replicas: 2

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - mreza
    deploy:
      replicas: 1

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mreza

networks:
  mreza:
    driver: bridge
